INSERT INTO ARTIKAL (CENA, KOLICINA, OPIS) VALUES (254, 12, 'MLEKO');
INSERT INTO KUPAC (KORISNICKO_IME, LOZINKA, IME, PREZIME, POL, DATUM_RODJENJA) VALUES ('saki', 'pw123', 'Sanja', 'Markovic', 'Z', '2001-04-14');
INSERT INTO DOSTAVLJAC (KORISNICKO_IME, LOZINKA, IME, PREZIME, POL, DATUM_RODJENJA) VALUES ('maki', 'sifra123', 'Marko', 'Jovanovic', 'M', '2001-06-10');
INSERT INTO MENADZER (KORISNICKO_IME, LOZINKA, IME, PREZIME, POL, DATUM_RODJENJA) VALUES ('pale', '1234', 'Nikola', 'Pantic', 'M', '2001-12-27');
INSERT INTO RESTORAN (NAZIV, TIP_RESTORANA) VALUES ('Atrijum', 'brza hrana');
INSERT INTO RESTORAN (NAZIV, TIP_RESTORANA) VALUES ('Baguette', 'francuski');